### ISSUE TITLE
Can not get it to run

### ISSUE THREAD

**Issue by funjspi** [arielfr/NodeMMO#1]
I get this error

`var io = require('socket.io.').listen(server, { log: false });
                                      ^

TypeError: require(...).listen is not a function
`

**Comment by arielfr** [comment]
¿Did you install the correct dependencies versions?

**Comment by funjspi** [comment]
i think so...

I rolled back socket.io to the version you have in the code. but still getting errors:

`/WEB/mmo/node_modules/socket.io/lib/store.js:35
Store.prototype.__proto__ = EventEmitter.prototype;
                                         ^

TypeError: Cannot read property 'prototype' of undefined
    at Object.<anonymous> (/WEB/mmo/node_modules/socket.io/lib/store.js:35:42)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/WEB/mmo/node_modules/socket.io/lib/manager.js:16:13)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
`

This game you have written sounds really intruiging and I want to check it out. Making games without canvas is fascinating to me haha!

I'll keep poking at it when I get the time and see what I can figure out.

**Comment by funjspi** [comment]
Okay figured it out. 

1) installed the dependencies listed on the package.json

2) fixed the errors by switching every instance of:
var EventEmitter = process. EventEmitter

To:
var EventEmitter = require('events')

After that it worked! Im going to poke around your code and see how you made this game because the map without a canvas is interesting to me.

**Comment by arielfr** [comment]
Thanks @funjspi i will fix it later
